# Generated by Django 4.0.2 on 2022-02-10 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter your user name less 30 symbols.', max_length=30, unique=True, verbose_name='User Name')),
                ('email', models.EmailField(help_text='Enter your e-mail.', max_length=254, unique=True, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('A', 'Allowed'), ('B', 'Blocked')], default='Allowed', max_length=30, verbose_name='Status account')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
