# Generated by Django 4.0.2 on 2022-02-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='user_id',
            new_name='id',
        ),
    ]
