# Generated by Django 4.0.2 on 2022-02-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userinformation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformationAdmin',
            fields=[
                ('userinformation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.userinformation')),
            ],
            bases=('users.userinformation',),
        ),
    ]
