# Generated by Django 4.0.2 on 2022-02-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_userinformationadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='status',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Blocked', 'Blocked')], default='Allowed', max_length=30, verbose_name='Status account'),
        ),
    ]
